index/urls.py
from django.urls import path
from .views import PostListView

app_name = 'index'

urlpatterns = [
    path('home/',PostListView.as_view(), name='home')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings 
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/", include("accounts.urls")),
    path('contact/', include('contact.urls',namespace='contact')),
    path('', include('index.urls',namespace='home')),
    path('post/', include('single_blog.urls',namespace='post')),
]

if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

single_blog/urls.py
from django.urls import path
from .views import PostDetailView, PostCreateView, YourPostsListView, PostUpdateView

app_name = 'single_blog'
urlpatterns = [
    path('add/',PostCreateView.as_view(),name='add-post'),
    path('my-posts/',YourPostsListView.as_view(),name='my-posts'),
    path('<str:slug>/',PostDetailView.as_view(),name='post'),
    path('edit/<str:slug>', PostUpdateView.as_view(),name='post-update'),
]

single_blog/models.py
import os
from uuid import uuid4
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify 
from accounts.models import Profile

def GetImageUploadTo(instance, ImageName):
    name, ext = os.path.splitext(ImageName)
    id = uuid4()
    return f"Posts/{id}{ext}"

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User,  on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=4000)
    PostImg = models.ImageField(upload_to=GetImageUploadTo)
    create_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=True, blank=True)
    def save(self): 
        id = uuid4()
        self.slug = slugify(self.title) +'-'+str(id)
        super().save()  
    
    def __str__(self):
        return self.title   

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.user.username)    

single_blog/forms.py
from django import forms
from .models import Comment, Post

class CommentForm(forms.ModelForm):
    """Form definition for Comment."""

    class Meta:
        """Meta definition for Commentform."""

        model = Comment
        fields = ('body',)

class DeleteConfirmationForm(forms.Form):
    confirmation = forms.BooleanField()
    slug = forms.CharField()

class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','description','PostImg'] 
    

single_blog/views.py
from typing import Any
from django.forms import BaseModelForm
from django.http import Http404, HttpRequest, HttpResponse, HttpResponseForbidden
from .models import Post,Comment 
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CommentForm, DeleteConfirmationForm ,UpdatePostForm
from django.views.generic.edit import FormMixin
from accounts.models import Profile
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.

@method_decorator(decorator=login_required,name='post')
class PostDetailView(DetailView,FormMixin):
    form_class = CommentForm
    http_method_names = ['get', 'post']
    model = Post
    template_name = "single_blog/post_detail.html"
    context_object_name = 'post'
    success_url = '#'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        comment = Comment.objects.filter(post = post)
        context.update({'comment':comment})
        
        return context
    
    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def form_valid(self, form: Any) -> HttpResponse:
        form.instance.post = self.get_object()
        form.instance.user = self.request.user
        profile = Profile.objects.get(user=self.request.user)
        form.instance.profile = profile
        print(form)

        form.save()
        return super().form_valid(form)
        
    
class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    template_name = "single_blog/add_post.html"
    fields = ['title', 'description','PostImg']
    @transaction.atomic
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        slug = self.object.slug
        url  = f'../{slug}/'
        return url


class YourPostsListView(LoginRequiredMixin,ListView,FormMixin):
    model = Post
    template_name = "single_blog/my_posts.html"
    paginate_by = 6
    context_object_name = 'posts'
    form_class = DeleteConfirmationForm
    success_url = '../../post/my-posts'
    def get_queryset(self):
        return Post.objects.filter(user=self.request.user).order_by('-create_at')
    
    
    def post(self,request, *args, **kwargs):
        self.object_list = self.get_queryset()
        form = self.get_form()
        
        if form.is_valid():
            return self.form_valid(form)
        else:
            print("Validating")

            return self.form_invalid(form)
    def form_valid(self, form: Any) -> HttpResponse:
        slug = form.cleaned_data.get('slug')
        try:
            obj = Post.objects.get(slug=slug)

        except Post.DoesNotExist:
            return Http404("No such post")
        if self.request.user.is_authenticated and obj.user == self.request.user:
            obj.delete()
            
        return super().form_valid(form)  

class PostUpdateView(LoginRequiredMixin,UpdateView):
    model = Post
    template_name = "single_blog/update_post.html"
    success_url = '../my-posts'
    form_class = UpdatePostForm

    def form_valid(self, form: Any) -> HttpResponse:
        try:
            obj = self.get_object()

        except Post.DoesNotExist:
            return Http404("No such post exists")
        if self.request.user.is_authenticated and obj.user == self.request.user:
            return super().form_valid(form)  
        else:
            
            return HttpResponseForbidden("You do not have permission to update this post.")
            

    

single_blog/templates/single_blog/add_post.html
{% extends 'base_generic.html' %}
{% load django_bootstrap5 %}
{% block title %}
add post.
{% endblock title %}

{% block body %}

<form method="post" enctype="multipart/form-data" style="width: 97%; margin-left: 15px;">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-outline-primary w-100" type="submit">Post</button>
</form>
{% endblock body %}

single_blog/templates/single_blog/my_posts.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}
My Posts
{% endblock title %}

{% block body %}
<!-- Page content-->
<div class="container mt-5">
    <!-- Post header-->
    <div class="mb-5 d-flex justify-content-between align-items-center">
        <header>
            <!-- Post title-->
            <h1 class="fw-bolder mb-1">Welcome to your Blog Posts!</h1>
        </header>

        <!-- btn -->
        <a href="{% url 'post:add-post' %}" class="btn btn-success"  >Create Post</a>
    </div>


    <!-- Nested row for non-featured blog posts-->
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4">
            <div class="card mb-4" style="height: 94%;">
                <a href="../{{post.slug}}"><img class="card-img-top" src="{{post.PostImg.url}}" alt="..." /></a>
                <div class="card-body">
                    <div class="small text-muted">{{post.create_at}}</div>
                    <h2 class="card-title h4">{{post.title}}</h2>
                    <p class="card-text">{{post.description|truncatechars:100}}</p>
                    <div>
                        <a href="{% url 'post:post-update' post.slug %}" class="btn btn-primary">Edit</a>
                        <button type="button" class="btn btn-danger" data-toggle="modal"
                            data-target="#modalDelete_{{post.id}}">Delete</button>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>




    {% for post in posts %}
    <!-- Modal Delete blog -->
    <div class="modal fade" id="modalDelete_{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete post</h5>
                    <button type="button" class="close btn" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true" style="font-size: 30px;">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-danger">
                    you are delete your post: {{post.title}}
                </div>
                <div class="modal-footer">
                    <form  method="post">
                        {% csrf_token %}
                        <div class="form-check" style="display: inline-block; margin-left: 60%;">
                            <input class="form-check-input" type="radio" name="confirmation" id="confirmation">
                            <label class="form-check-label" for="confirmation">
                                Confirmation
                            </label>
                        </div>
                        <input type="hidden" name="slug" value="{{ post.slug }}">
                        <button  type="submit" class="btn btn-danger">Delete</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endfor %}

</div>
</div>
<!-- Pagination-->
{% if page_obj.has_other_pages %}
<nav aria-label="Pagination">
    <hr class="my-0" />
    <ul class="pagination justify-content-center my-4">
        {% if page_obj.has_previous %}
        <li class="page-item "><a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1"
                aria-disabled="true">Newer</a></li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
        <li class="page-item 
                {% if page_obj.number == i %}
                active
                {% endif %}
                     " aria-current="page"><a class="page-link" href="?page={{i}}">{{i}}</a></li>

        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Older</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}
</div>


{% endblock body %}

single_blog/templates/single_blog/post_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}
{{post.title}}
{% endblock title %}

{% block body %}
<!-- Page content-->
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{post.title}}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Posted on {{post.create_at}}</div>
                    <div class="text-muted fst-italic mb-2">by {{post.user.username}}</div>
                </header>
                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded" src="{{post.PostImg.url}}" alt="..." /></figure>
                <!-- Post content-->
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{post.description}}</p>
                </section>
            </article>
            <!-- Comments section-->
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body bg-dark " style=" color: aliceblue; max-height: 400px; overflow: auto;">
                        <!-- Comment form-->
                        <form class="mb-4" method="post" style="color: aliceblue;">
                            {% csrf_token %}
                            <div class="mb-3"><label class="form-label" for="id_body">comment</label><textarea name="body" cols="40" rows="7" class="form-control" placeholder="Join the discussion and leave a comment!" required id="id_body"></textarea>                     
                            <button class="btn btn-outline-primary w-100" type="submit">Post</button>
                        </form>
                        <!-- Single comment-->
                        {% if comment %}

                        
                        {% for comment_  in comment %}
                            
                        
                            
                        <div class="d-flex mb-4 text-light">
                            <!-- Parent comment-->                               
                            <div class="flex-shrink-0" ><img class="rounded-circle" src="
                            {% if comment_.profile.ProfileImg %}
                            
                            {{comment_.profile.ProfileImg.url}}
                            {% endif %}
                                " alt="..." style="width: 50px; height: 50px;">
                            </div>
                            <div class="ms-3">
                                <div class="fw-bold">{{comment_.user.username}}</div>
                                {{comment_.body}}
                            </div>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </section>

        </div>
    </div>
    </section>
</div>
<div class="col-lg-2"></div>
</div>
</div>
{% endblock body %}

single_blog/templates/single_blog/update_post.html
{% extends 'base_generic.html' %}
{% load django_bootstrap5 %}
{% block title %}
add post.
{% endblock title %}

{% block body %}

<form method="post" enctype="multipart/form-data" style="width: 97%; margin-left: 15px;">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-outline-primary w-100" type="submit">Post</button>
</form>
{% endblock body %}