contact/urls.py
from django.urls import path
from .views import ContactView, SuccessContact

app_name = 'contact'

urlpatterns = [
    path('',ContactView.as_view(),name='contact-us'),
    path('success/',SuccessContact.as_view(),name='contact_success'),
]

index/urls.py
from django.urls import path
from .views import PostListView

app_name = 'index'

urlpatterns = [
    path('home/',PostListView.as_view(), name='home')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings 
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/", include("accounts.urls")),
    path('contact/', include('contact.urls',namespace='contact')),
    path('', include('index.urls',namespace='home')),
    path('post/', include('single_blog.urls',namespace='post')),
]

if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

single_blog/urls.py
from django.urls import path
from .views import PostDetailView, PostCreateView, YourPostsListView, PostUpdateView

app_name = 'single_blog'
urlpatterns = [
    path('add/',PostCreateView.as_view(),name='add-post'),
    path('my-posts/',YourPostsListView.as_view(),name='my-posts'),
    path('<str:slug>/',PostDetailView.as_view(),name='post'),
    path('edit/<str:slug>', PostUpdateView.as_view(),name='post-update'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock title %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-profiles.min.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body class="d-flex flex-column min-vh-100 ">
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home:home' %}">Logo</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="fa fa-bars"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'home:home' %}">Home</a></li>
                    …
                    {% if user.is_authenticated %}
                    <li class="nav-link ">welcome: {{ user.get_username }}</li>
                    <li class="nav-item"><a href="{% url 'profile' %}" class="nav-link">Profile</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'post:my-posts' %}" class="nav-link">Your Posts</a>
                    </li>
                    <li class="nav-item">
                        <form id="logout-form" method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link nav-link">Logout</button>
                        </form>
                    </li>
                    <li class="nav-item"><a href="{% url 'post:add-post' %}" class="nav-link">Add-Post</a>
                    </li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a>
                    </li>
                    <li class="nav-item"><a href="{% url 'signup' %}" class="nav-link">Signup</a></li>
                    {% endif %}
                    <li class="nav-item"><a href="{% url 'contact:contact-us' %}" class="nav-link">Contact-US</a>
                    </li>
                    …
                </ul>
            </div>
        </div>
    </nav>
    

    {% block body %}

    {% endblock body %}
    <!-- Footer-->
    <footer class="py-5 bg-dark footer mt-auto py-3 bg-dark text-white">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; blog 2024</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>

</html>

templates/base_generic.html
{% extends 'base.html' %}
{% block body %}
<div class="container mt-5 " >
    <div class="row">
        {% block content %}
          
        {% endblock content %}
    </div>
</div>
{% endblock body %}